[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.0.0 --activate",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
