name: CI

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ master ]

<<<<<<< HEAD
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
=======
permissions:
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      pnpm_store: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
>>>>>>> b441709ea5fb286480a5eea79547c67ea0aca487
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

<<<<<<< HEAD
      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Setup pnpm 9
=======
      - name: Install pnpm
>>>>>>> b441709ea5fb286480a5eea79547c67ea0aca487
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

<<<<<<< HEAD
      - name: Install deps
        run: pnpm -w install --frozen-lockfile

      - name: Typecheck
        run: pnpm -w typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with: { version: 9, run_install: false }
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Lint
        run: pnpm -w lint

  test:
    name: Tests (Vitest + Coverage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with: { version: 9, run_install: false }
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Run tests
        run: pnpm -w test:ci
=======
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install deps
        run: pnpm install --frozen-lockfile

  typecheck:
    name: Typecheck
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Type check
        run: pnpm typecheck

  lint:
    name: Lint
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint

  test:
    name: Tests (Vitest + Coverage)
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run unit tests with coverage
        run: pnpm test:ci
>>>>>>> b441709ea5fb286480a5eea79547c67ea0aca487

  build:
    name: Build (UI)
    needs: [typecheck, lint, test]
    runs-on: ubuntu-latest
<<<<<<< HEAD
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with: { version: 9, run_install: false }
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Build
=======
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - name: Restore pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build web app
>>>>>>> b441709ea5fb286480a5eea79547c67ea0aca487
        run: pnpm -w build
