name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm -w install --frozen-lockfile

      - name: Typecheck
        run: pnpm -w typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with: { version: 9, run_install: false }
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Lint
        run: pnpm -w lint

  test:
    name: Tests (Vitest + Coverage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with: { version: 9, run_install: false }
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Run tests
        run: pnpm -w test:ci

  build:
    name: Build (UI)
    needs: [typecheck, lint, test]
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: corepack enable
      - uses: pnpm/action-setup@v4
        with: { version: 9, run_install: false }
      - name: Install deps
        run: pnpm -w install --frozen-lockfile
      - name: Build
        run: pnpm -w build