name: CI

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./apps/web typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./apps/web lint

  test:
    name: Tests (Vitest + Coverage)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./apps/web test:ci

  build:
    name: Build (UI)
    needs: [typecheck, lint, test]
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter ./apps/web build